name: fast_tenders
workspace:
  - core
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ./core
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  supabase_flutter: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  go_router: ^13.2.5
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  share_plus: ^12.0.1
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env